
export const CONCERT_DETAILS_FETCH = 'CONCERT_DETAILS_FETCH'
export const CONCERT_DETAILS_FETCH_FAILURE = 'CONCERT_DETAILS_FETCH_FAILURE'

export const  CONCERT_DETAILS_FETCH_SUCCESS ='CONCERT_DETAILS_FETCH_SUCCESS'
export const  CONCERT_DETAILS_FETCH_ERROR='CONCERT_DETAILS_FETCH_ERROR'
export const  FILTERS_UPDATE='FILTERS_UPDATE'
